BIN_DIR = $$OUT_PWD/bin
BUILDFILES_DIR = $$OUT_PWD/build_files

DESTDIR = $$BIN_DIR/$$SUBPROJECT_DIR
OBJECTS_DIR = $$BUILDFILES_DIR/obj/$$SUBPROJECT_DIR
MOC_DIR = $$BUILDFILES_DIR/moc/$$SUBPROJECT_DIR
RCC_DIR = $$BUILDFILES_DIR/rcc/$$SUBPROJECT_DIR
UI_DIR = $$BUILDFILES_DIR/ui/$$SUBPROJECT_DIR

mkpath($$DESTDIR)
mkpath($$OBJECTS_DIR)
mkpath($$MOC_DIR)
mkpath($$RCC_DIR)
mkpath($$UI_DIR)
